import React, { useContext, useEffect, useRef, useState } from "react";
import TransactionCard from "./TransactionCard";
import expenseContext from "../context/expenses/expenseContext";
import { useNavigate } from "react-router-dom";
import DateDropdown from "./DateDropdown";
import PieChart from "./PieChart";
import LineChart from "./LineChart";
import LineChart2 from "./LineChart2";
import { MdDelete } from "react-icons/md";
import ExportToExcel from "./Excel";